#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/../.." && pwd)
TARGET_FILE=${1:-"${REPO_ROOT}/test/.env"}
DEPLOYER_ADDRESSES_URL=${DEPLOYER_ADDRESSES_URL:-http://127.0.0.1:8000/addresses.env}

PROCESS_REGISTRY=""
STATE_TRANSITION_VERIFIER=""
RESULTS_REGISTRY=""
RESULTS_VERIFIER=""

TMP_ADDRESSES_FILE=$(mktemp)
if curl -fsS "${DEPLOYER_ADDRESSES_URL}" -o "${TMP_ADDRESSES_FILE}"; then
  # shellcheck disable=SC1090
  . "${TMP_ADDRESSES_FILE}"
fi
rm -f "${TMP_ADDRESSES_FILE}"

# Backward compatibility: prefer explicit RESULTS_VERIFIER, fallback to RESULTS_REGISTRY.
if [[ -z "${RESULTS_VERIFIER}" && -n "${RESULTS_REGISTRY}" ]]; then
  RESULTS_VERIFIER="${RESULTS_REGISTRY}"
fi

cat > "${TARGET_FILE}" <<EOF
SEQUENCER_API_URL=http://127.0.0.1:9090
CENSUS_API_URL=http://127.0.0.1:8080
RPC_URL=http://127.0.0.1:8545
PRIVATE_KEY=ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
PROCESS_REGISTRY=${PROCESS_REGISTRY}
STATE_TRANSITION_VERIFIER=${STATE_TRANSITION_VERIFIER}
RESULTS_VERIFIER=${RESULTS_VERIFIER}
TIMEOUT=600000
EOF

echo "Wrote integration env file to ${TARGET_FILE}"
