/**
 * @fileoverview BabyJubJub in circomlib twisted Edwards form,
 * `a*x^2 + y^2 = 1 + d*x^2*y^2` with `a = 168700`, `d = 168696` and generator
 * B8, as davinci-zkvm `crypto/babyjubjub.rs`. This is the form of the
 * registry, the sequencer API, the ballot circuit and the guest; the reduced
 * form (RTE) only appears in the DKG, see `dkg.ts`.
 */

import { BN254_FR, assertFieldElement, mod, modInverse } from './field';

/** An affine BabyJubJub point in circomlib TE coordinates, both below p. */
export interface BjjPoint {
  x: bigint;
  y: bigint;
}

const A = 168700n;
const D = 168696n;

/** The iden3 base point B8, generator of the prime-order subgroup. */
export const BJJ_B8: Readonly<BjjPoint> = Object.freeze({
  x: 5299619240641551281634865583518297030282874472190772894086521144482721001553n,
  y: 16950150798460657717958625567821834550301663161624707787222815936182638968203n,
});

/** The group identity `(0, 1)`. */
export const BJJ_IDENTITY: Readonly<BjjPoint> = Object.freeze({ x: 0n, y: 1n });

/** Order `l` of the subgroup generated by B8 (the curve order is `8 * l`). */
export const BJJ_SUBGROUP_ORDER =
  2736030358979909402780800718157159386076813972158567259200215660948447373041n;

// Extended coordinates (X:Y:T:Z): x = X/Z, y = Y/Z, T = XY/Z.
interface Ext {
  x: bigint;
  y: bigint;
  t: bigint;
  z: bigint;
}

const P = BN254_FR;
const EXT_IDENTITY: Ext = { x: 0n, y: 1n, t: 0n, z: 1n };

function toExt(p: BjjPoint): Ext {
  return { x: p.x, y: p.y, t: (p.x * p.y) % P, z: 1n };
}

// add-2008-hwcd, complete on this curve (a square, d non-square).
function extAdd(p: Ext, q: Ext): Ext {
  const a = (p.x * q.x) % P;
  const b = (p.y * q.y) % P;
  const c = (((D * p.t) % P) * q.t) % P;
  const d = (p.z * q.z) % P;
  const e = mod((p.x + p.y) * (q.x + q.y) - a - b);
  const f = mod(d - c);
  const g = (d + c) % P;
  const h = mod(b - A * a);
  return { x: (e * f) % P, y: (g * h) % P, t: (e * h) % P, z: (f * g) % P };
}

// dbl-2008-hwcd.
function extDouble(p: Ext): Ext {
  const a = (p.x * p.x) % P;
  const b = (p.y * p.y) % P;
  const c = (2n * p.z * p.z) % P;
  const d = (A * a) % P;
  const e = mod((p.x + p.y) * (p.x + p.y) - a - b);
  const g = (d + b) % P;
  const f = mod(g - c);
  const h = mod(d - b);
  return { x: (e * f) % P, y: (g * h) % P, t: (e * h) % P, z: (f * g) % P };
}

function toAffine(p: Ext): BjjPoint {
  const zi = modInverse(p.z);
  return { x: (p.x * zi) % P, y: (p.y * zi) % P };
}

/** True when both coordinates are below p and the point satisfies the curve equation. */
export function bjjIsOnCurve(p: BjjPoint): boolean {
  if (p.x < 0n || p.x >= P || p.y < 0n || p.y >= P) return false;
  const x2 = (p.x * p.x) % P;
  const y2 = (p.y * p.y) % P;
  return (A * x2 + y2) % P === (1n + ((D * x2) % P) * y2) % P;
}

function assertOnCurve(p: BjjPoint, what: string): void {
  if (!bjjIsOnCurve(p)) throw new RangeError(`${what} is not a BabyJubJub point`);
}

/** True for the identity `(0, 1)`. */
export function bjjIsIdentity(p: BjjPoint): boolean {
  return p.x === 0n && p.y === 1n;
}

/** `p + q`. Both must be on the curve. */
export function bjjAdd(p: BjjPoint, q: BjjPoint): BjjPoint {
  assertOnCurve(p, 'point');
  assertOnCurve(q, 'point');
  return toAffine(extAdd(toExt(p), toExt(q)));
}

/** The group inverse `(-x, y)`. */
export function bjjNeg(p: BjjPoint): BjjPoint {
  assertOnCurve(p, 'point');
  return { x: mod(-p.x), y: p.y };
}

/**
 * `k * p` for any non-negative scalar, unreduced (the same group element as
 * reducing `k` by the point's order). Not constant time, like any JS bigint code.
 */
export function bjjMul(p: BjjPoint, k: bigint): BjjPoint {
  assertOnCurve(p, 'point');
  if (k < 0n) throw new RangeError('scalar must be non-negative');
  const base = toExt(p);
  let acc = EXT_IDENTITY;
  const bits = k.toString(2);
  for (let i = 0; i < bits.length; i++) {
    acc = extDouble(acc);
    if (bits[i] === '1') acc = extAdd(acc, base);
  }
  return toAffine(acc);
}

/** `k * B8`. */
export function bjjMulBase(k: bigint): BjjPoint {
  return bjjMul(BJJ_B8, k);
}

/**
 * True when `p` is on the curve and `l * p` is the identity. The identity
 * itself passes; see {@link isValidEncryptionKey} for a usable key.
 */
export function bjjInSubgroup(p: BjjPoint): boolean {
  return bjjIsOnCurve(p) && bjjIsIdentity(bjjMul(p, BJJ_SUBGROUP_ORDER));
}

/**
 * The checks the ballot circuit and the sequencer apply to an election key:
 * on the curve, not the identity and in the prime-order subgroup.
 */
export function isValidEncryptionKey(p: BjjPoint): boolean {
  return bjjIsOnCurve(p) && !bjjIsIdentity(p) && bjjInSubgroup(p);
}

/** A point from its coordinates, checked to be canonical and on the curve. */
export function toBjjPoint(x: bigint, y: bigint): BjjPoint {
  const p = { x: assertFieldElement(x, 'x'), y: assertFieldElement(y, 'y') };
  assertOnCurve(p, 'point');
  return p;
}
